version: "3"

services:

  postgres:
    container_name: kupipodariday-db
    image: "postgres:12.12-alpine"
    restart: "unless-stopped"
    networks:
      - db-network
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file: backend/.env

  backend:
    container_name: kupipodariday-back
    build: backend
    restart: "always"
    networks:
      - db-network
      - frontend-network
    env_file: backend/.env
    ports:
      - "4000:3000"
    depends_on:
      - postgres

  frontend:
    container_name: kupipodariday-front
    build: frontend
   restart: "always"
    networks:
      - frontend-network
    ports:
      - "8081:80"

networks:
  db-network:
  frontend-network:


volumes:
  db-volume:


